services:
  xray-gw:
    build:
      context: ./
      args:
        SUB_URL: "https://remna.wave.url/sub/*******/json"
        XRAY_VERSION: "26.2.6"
    container_name: xray-gw
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # для TPROXY иногда требуется:
    # privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.route_localnet=1
    ports:
      # если надо публиковать порты приложений — публикуй их здесь
      # потому что app будет в том же namespace
      - "8080:8080"
    restart: unless-stopped

  test:
    image: curlimages/curl:8.6.0
    network_mode: "service:xray-gw"
    depends_on: [xray-gw]
    command: sleep 3600

  app:
    image: your/app:latest
    network_mode: "service:xray-gw"
    depends_on:
      - xray-gw
    restart: unless-stopped